### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by thedrow** [abargnesi/rantly#16]
There has been some changes since the last release. Can we release again?

**Comment by abargnesi** [comment]
Agreed there have been a few changes, some big, some small. I'll cut a new release at 1.0.0 since there is a breaking change due to the removal of `Array#shrink` (see #10).

**Comment by abargnesi** [comment]
Released [version 1.0.0](https://github.com/abargnesi/rantly/releases/tag/1.0.0). Pushed to RubyGems.
