### ISSUE TITLE
Size greater than

### ISSUE THREAD

**Issue by Ana06** [abargnesi/rantly#19]
I would like to generate string with size greater than 200, is that possible? :confused:

**Comment by abargnesi** [comment]
Hello and welcome!

Yes you can generate a string greater than `200` by applying `sized(range({LOWER BOUND}, {UPPER BOUND}))` over a `string`. You can then use a `guard` condition to exclude the lower bound.

For example to generate a string longer than `200` do:

```ruby
# keep in mind default for upper bound is Rantly::INTEGER_MAX (2305843009213693951)
Rantly {
  sized(range(200)) {
    guard(@size > 200)
    string
  }
}
```

**Comment by Ana06** [comment]
Thank you @abargnesi 
It works but the problem it is that it takes too long to generate such big strings.

**Comment by abargnesi** [comment]
You will want to pick an upper bound that is reasonable for your problem.

Additionally the implementation is inefficient due to excessive string concatenation and randomization. 

The following re-implementation shows a constant 6 times speed up relative to the size of string.

```ruby
#!/usr/bin/env ruby
require 'benchmark/ips'
require 'rantly'

class Rantly

  def string2(char_class=:print)
    chars = case char_class
            when Regexp
              Chars.of(char_class)
            when Symbol
              Chars::CLASSES[char_class]
            end
    raise "bad arg" unless chars
    str = Array.new(size)
    i   = 0
    while i < size
      str[i] = chars.sample
      i += 1
    end
  end
end

[1000, 10_000, 100_000, 1_000_000].each do |size|
  Benchmark::ips do |bm|

    bm.report("rantly #{size}") do
      Rantly { sized(size) { string } }
    end

    bm.report("range sample #{size}") do
      Rantly { sized(size) { string2 } }
    end

    bm.compare!
  end
end
```

This pre-allocates the array to `size` to avoid resizing and uses [Array#sample](https://ruby-doc.org/core-2.4.0/Array.html#method-i-sample) within a while loop.

**Comment by Ana06** [comment]
@abargnesi 

> The following re-implementation shows a constant 6 times speed up relative to the size of string.

Great! Will you update this in the project? :slightly_smiling_face:

**Comment by abargnesi** [comment]
We can safely include this improvement as it does not change the API.
