### ISSUE TITLE
New release wanted

### ISSUE THREAD

**Issue by Ana06** [abargnesi/rantly#25]
When there will be a new release? I think that https://github.com/abargnesi/rantly/commit/4a0b3881ead86b0a265c992607f815c4dd904427 and https://github.com/abargnesi/rantly/commit/4a9a809bd3d683606aa53867d18f95466c9884bd are important enough to have a new release.

**Comment by abargnesi** [comment]
Thanks for the check. I put out [1.1.0](https://rubygems.org/gems/rantly/versions/1.1.0) and updated the changelog.

**Comment by Ana06** [comment]
@abargnesi thanks! :wink:
