### ISSUE TITLE
RubyGems does not list this as the official repo

### ISSUE THREAD

**Issue by AaronLasseigne** [abargnesi/rantly#5]
RubyGems still lists http://github.com/hayeah/rantly as the homepage.

**Comment by abargnesi** [comment]
Thanks for the catch.

I have updated the *Source Code* link, but the *Homepage* can only be updated by a gem push. I'm getting up to speed and working on #2 and #3 before a push.

**Comment by AaronLasseigne** [comment]
Sure thing. Good luck with taking over.
