### ISSUE TITLE
What is the advantage over Faker

### ISSUE THREAD

**Issue by vveliev** [abargnesi/rantly#6]
what is the benefit of using rantly over faker ?!

**Comment by abargnesi** [comment]
Having briefly looked at [faker](https://github.com/stympy/faker) it seems better suited to generating random, human-readable values for higher-level concepts (e.g. names, companies, addresses). Rantly helps test application behavior using random data.

Rantly Capabilities
- Generate data for core types (`boolean`, `string`, `integer`, `float`, `array`, `hash`, etc..). The generated values fits the domain of the type.

```ruby
# Returns an Integer within the inclusive range [0, 10].
Rantly.value { range(0,10) }
```

- Compose data generators for more complex types.

```ruby
# Returns a dictionary with 10 entries. The keys are alphanumeric strings of length and the values are Integers within the inclusive range [0, 10].
Rantly.value {
  dict(10) {
    [
      sized(10) { string(:alpha) },
      range(0, 10)
    ]
  }
}
```

- Extensions to ruby test frameworks (`test/unit`, `minitest`, `rspec`) for property testing. This allows you to test that a property, or behavior, of your application holds for randomly generated data.

```ruby
# Property test to assert pagination correctly computes current page given start offset of collection, page_size, and total items in collection.
it 'when paging' do
  property_of {
    Rantly.value(1000) {
      start       = range(0, 10000)
      page_size   = range(1, 10000)
      total       = range(1, 10000)

      guard start <= total

      [start, page_size, total]
    }
  }.check(25000, 1000) { |start, page_size, total|
    pager = Pager.new(start, page_size, total)
    expect(pager.current_page).to eql ((start + page_size) / page_size.to_f).floor
  }
end
```

Hope that helps!

**Comment by vveliev** [comment]
Thanks !! it does
